version: '3'
services:
    nginx:
        image: nginx:1.14
        depends_on:
            - php-fpm
        links:
            - php-fpm
        environment:
            - NGINX_PORT=80
            - FASTCGI_HOST=php-fpm
            - FASTCGI_PORT=9000
            - DOCUMENT_ROOT=/usr/local/src/wor/public
            - UPLOAD_MAX_FILESIZE=50M
        ports:
            - 8010:80
        volumes:
            - ./stack/nginx/templates/default.conf.template:/etc/nginx/conf.d/default.conf.template
            - ./stack/nginx/entrypoint.sh:/entrypoint.sh
            - .:/usr/local/src/wor
        command: "/bin/bash /entrypoint.sh"

    database:
        image: mysql:5.7
        env_file:
            - ./stack/environment/development/database.env
        ports:
            - 8011:3306
        command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
        volumes:
            - data:/var/lib/mysql

    php-fpm:
        build: ./
        depends_on:
            - database
        links:
            - database
        command: bash -c "/usr/bin/supervisord && php-fpm7.2 -c /etc/php/7.2/cli/php.ini"
        volumes:
            - .:/usr/local/src/wor
            - ./stack/supervisord/development/conf.d/:/etc/supervisor/conf.d/
            - ./stack/cron/:/etc/cron.d
        working_dir: /usr/local/src/wor
        ports:
            - "9010:9001"
        env_file:
            - ./stack/environment/development/php-fpm.env
            - ./stack/environment/development/mail.env

    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - "1029:1025"
            - "8029:8025"
volumes:
    data: {}
